services:
  - type: web
    name: coffee-shop-api
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Key
        generateValue: true
      - key: CorsOrigins
        value: https://teddyyee-coffee-shop-frontend.vercel.app
      - key: ConnectionStrings__DefaultConnection
        sync: false
